apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: customer-order-integration
spec:
  topic: order-service
  route: /customer-operations
  pubsubname: customer-order-integration
scopes:
- order-service